dark:
  background_color: darkslategrey
  text_color: white
default:
  labelsize: 17
  digitsize: 14
  textsize: 23
  titlesize: 25
  naxeslabels: 5
  ncbarlabels: 5
  contourthickness: 0.8
  background_color: white
  text_color: black
  interpolation: none